---
# performance-config.yaml - Performance optimization settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-config
  namespace: vibe-detector
data:
  gunicorn.conf.py: |
    import multiprocessing

    # Workers
    workers = multiprocessing.cpu_count() * 2 + 1
    worker_class = 'eventlet'
    worker_connections = 1000

    # Timeouts
    timeout = 30
    graceful_timeout = 30
    keepalive = 5

    # Request limits
    max_requests = 1000
    max_requests_jitter = 50

    # Security
    limit_request_line = 4094
    limit_request_fields = 100
    limit_request_field_size = 8190

    # Logging
    accesslog = '-'
    errorlog = '-'
    loglevel = 'info'

    # StatsD integration for metrics
    statsd_host = 'localhost:8125'
    statsd_prefix = 'vibe_detector'

    def when_ready(server):
        server.log.info("Server is ready. Spawning workers")

    def worker_int(worker):
        worker.log.info("Worker received INT or QUIT signal")

    def pre_fork(server, worker):
        server.log.info(f"Forking worker {worker.pid}")

    def post_fork(server, worker):
        server.log.info(f"Worker spawned {worker.pid}")

    def worker_abort(worker):
        worker.log.info(f"Worker {worker.pid} aborted")
