name: VCC Analysis
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install VCC
        run: pip install -r requirements.txt
      - name: Run VCC Analysis
        run: python vibe_code_detector.py .